const PRESALE_FACTORY_ABI = [
  {
    type: "constructor",
    inputs: [
      {
        name: "_creationFee",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_feeToken", type: "address", internalType: "address" },
      {
        name: "_housePercentage",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_houseAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "BASIS_POINTS",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "createPresale",
    inputs: [
      {
        name: "_options",
        type: "tuple",
        internalType: "struct Presale.PresaleOptions",
        components: [
          {
            name: "tokenDeposit",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "hardCap", type: "uint256", internalType: "uint256" },
          { name: "softCap", type: "uint256", internalType: "uint256" },
          { name: "min", type: "uint256", internalType: "uint256" },
          { name: "max", type: "uint256", internalType: "uint256" },
          {
            name: "presaleRate",
            type: "uint256",
            internalType: "uint256",
          },
          { name: "start", type: "uint256", internalType: "uint256" },
          { name: "end", type: "uint256", internalType: "uint256" },
          {
            name: "currency",
            type: "address",
            internalType: "address",
          },
          {
            name: "whitelistType",
            type: "uint8",
            internalType: "enum Presale.WhitelistType",
          },
          {
            name: "merkleRoot",
            type: "bytes32",
            internalType: "bytes32",
          },
          {
            name: "nftContractAddress",
            type: "address",
            internalType: "address",
          },
        ],
      },
      { name: "_token", type: "address", internalType: "address" },
    ],
    outputs: [
      {
        name: "presaleAddress",
        type: "address",
        internalType: "address",
      },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "createdPresales",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creationFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAllPresales",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getCreationFee",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHouseAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getHousePercentage",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPresaleAt",
    inputs: [{ name: "index", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPresaleCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "houseAddress",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "housePercentage",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFeeConfiguration",
    inputs: [
      {
        name: "_newCreationFee",
        type: "uint256",
        internalType: "uint256",
      },
      { name: "_newFeeToken", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setHouseConfiguration",
    inputs: [
      {
        name: "_newHousePercentage",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "_newHouseAddress",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawFees",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "FeeConfigurationChanged",
    inputs: [
      {
        name: "newCreationFee",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newFeeToken",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "HouseConfigurationChanged",
    inputs: [
      {
        name: "newHousePercentage",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "newHouseAddress",
        type: "address",
        indexed: false,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "PresaleCreated",
    inputs: [
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "presaleContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "start",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "end",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "FeePaymentFailed", inputs: [] },
  { type: "error", name: "IndexOutOfBounds", inputs: [] },
  { type: "error", name: "InvalidFeeConfiguration", inputs: [] },
  { type: "error", name: "InvalidHouseConfiguration", inputs: [] },
  {
    type: "error",
    name: "OwnableInvalidOwner",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "OwnableUnauthorizedAccount",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ReentrancyGuardReentrantCall", inputs: [] },
  {
    type: "error",
    name: "SafeERC20FailedOperation",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
];

module.exports = {
  PRESALE_FACTORY_ABI,
};
